<?php
/**
 * This file is automatically generated from Chatwing API
 * @author chatwing
 */
if ( ! defined( 'ABSPATH' ) ) exit; // Exit if accessed directly

return array(
    'app/float_ui/list' => array(
        'type' => 'get',
        'auth' => true
    ),
    'chatbox/read' => array(
        'type' => 'get',
        'auth' => true
    ),
);